"""initial schema

Revision ID: 4332699ab7a3
Revises: 
Create Date: 2026-05-02 12:02:58.957359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4332699ab7a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('sector', sa.Enum('FINTECH', 'HEALTHTECH', 'EDTECH', 'ECOMMERCE', 'LOGISTICS', 'AGRITECH', 'SAAS', 'INSURTECH', 'PROPTECH', 'OTHER', name='sector'), nullable=False),
    sa.Column('size', sa.Enum('SOLO', 'MICRO', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', name='companysize'), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'PRE_SEED', 'SEED', 'SERIES_A', 'SERIES_B', 'SERIES_C_PLUS', 'BOOTSTRAPPED', 'ESTABLISHED', name='companystage'), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STARTER', 'GROWTH', 'AUDIT_READY', name='subscriptiontier'), nullable=False),
    sa.Column('billing_currency', sa.Enum('NGN', 'KES', 'ZAR', 'GHS', 'USD', name='billingcurrency'), nullable=False),
    sa.Column('paystack_customer_code', sa.String(length=255), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('frameworks',
    sa.Column('code', sa.Enum('SOC2', 'ISO_27001', 'NDPA', 'NDPR', 'CBN_CYBER', 'POPIA', 'KENYA_DPA', 'GHANA_DPA', 'PCI_DSS', name='frameworkcode'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_code'), 'frameworks', ['code'], unique=True)
    op.create_table('controls',
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id', 'code', name='uq_framework_control_code')
    )
    op.create_index(op.f('ix_controls_framework_id'), 'controls', ['framework_id'], unique=False)
    op.create_table('policies',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('template_code', sa.Enum('INFORMATION_SECURITY', 'ACCESS_CONTROL', 'DATA_PROTECTION', 'DATA_RETENTION', 'INCIDENT_RESPONSE', 'ACCEPTABLE_USE', 'BUSINESS_CONTINUITY', 'VENDOR_MANAGEMENT', 'CHANGE_MANAGEMENT', 'SECURE_DEVELOPMENT', 'PASSWORD', 'REMOTE_WORK', 'BACKUP_RECOVERY', 'PRIVACY', 'SECURITY_AWARENESS', name='policytemplatecode'), nullable=False),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='policystatus'), nullable=False),
    sa.Column('rendered_variables', sa.JSON(), nullable=False),
    sa.Column('framework_codes', sa.JSON(), nullable=False),
    sa.Column('control_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_company_id'), 'policies', ['company_id'], unique=False)
    op.create_index(op.f('ix_policies_template_code'), 'policies', ['template_code'], unique=False)
    op.create_table('subscriptions',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'STARTER', 'GROWTH', 'AUDIT_READY', name='subscriptiontier'), nullable=False),
    sa.Column('interval', sa.Enum('MONTHLY', 'ANNUALLY', name='billinginterval'), nullable=False),
    sa.Column('currency', sa.Enum('NGN', 'KES', 'ZAR', 'GHS', 'USD', name='billingcurrency'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('paystack_plan_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_subscription_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_customer_code', sa.String(length=100), nullable=True),
    sa.Column('paystack_email_token', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'NON_RENEWING', 'ATTENTION', 'CANCELLED', 'COMPLETED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_company_id'), 'subscriptions', ['company_id'], unique=False)
    op.create_index('ix_subscriptions_company_status', 'subscriptions', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_paystack_subscription_code'), 'subscriptions', ['paystack_subscription_code'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_table('users',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('questionnaire_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'SUBMITTED', 'PROCESSING', 'COMPLETED', 'FAILED', name='assessmentstatus'), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('overall_risk_score', sa.Integer(), nullable=True),
    sa.Column('soc2_readiness_score', sa.Integer(), nullable=True),
    sa.Column('ndpa_compliance_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_company_id'), 'assessments', ['company_id'], unique=False)
    op.create_table('billing_events',
    sa.Column('paystack_event_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.Enum('CHARGE_SUCCESS', 'CHARGE_FAILED', 'SUBSCRIPTION_CREATE', 'SUBSCRIPTION_DISABLE', 'SUBSCRIPTION_NOT_RENEW', 'SUBSCRIPTION_EXPIRING_CARDS', 'INVOICE_CREATE', 'INVOICE_UPDATE', 'INVOICE_PAYMENT_FAILED', 'CUSTOMER_IDENTIFICATION_FAILED', 'CUSTOMER_IDENTIFICATION_SUCCESS', 'OTHER', name='billingeventtype'), nullable=False),
    sa.Column('raw_event_name', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_company_id'), 'billing_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_billing_events_event_type'), 'billing_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_events_paystack_event_id'), 'billing_events', ['paystack_event_id'], unique=True)
    op.create_index(op.f('ix_billing_events_subscription_id'), 'billing_events', ['subscription_id'], unique=False)
    op.create_table('control_mappings',
    sa.Column('source_control_id', sa.String(length=36), nullable=False),
    sa.Column('target_control_id', sa.String(length=36), nullable=False),
    sa.Column('strength', sa.Enum('EQUIVALENT', 'PARTIAL', 'RELATED', name='mappingstrength'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_control_id', 'target_control_id', name='uq_control_mapping_pair')
    )
    op.create_index(op.f('ix_control_mappings_source_control_id'), 'control_mappings', ['source_control_id'], unique=False)
    op.create_index(op.f('ix_control_mappings_target_control_id'), 'control_mappings', ['target_control_id'], unique=False)
    op.create_table('evidence',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('EXTERNAL_LINK', 'POLICY_REF', 'SCREENSHOT_URL', 'NARRATIVE', 'FILE_UPLOAD', name='evidencekind'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'REJECTED', name='evidencestatus'), nullable=False),
    sa.Column('framework_code', sa.String(length=50), nullable=False),
    sa.Column('control_code', sa.String(length=50), nullable=False),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('referenced_policy_id', sa.String(length=36), nullable=True),
    sa.Column('narrative_text', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referenced_policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_company_id'), 'evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_evidence_control_code'), 'evidence', ['control_code'], unique=False)
    op.create_index(op.f('ix_evidence_framework_code'), 'evidence', ['framework_code'], unique=False)
    op.create_table('policy_acknowledgments',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('acknowledged_text', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'user_id', name='uq_policy_user_ack')
    )
    op.create_index(op.f('ix_policy_acknowledgments_policy_id'), 'policy_acknowledgments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgments_user_id'), 'policy_acknowledgments', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.Enum('INITIAL', 'REASSESSMENT', 'QUARTERLY', 'AD_HOC', name='reporttype'), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('risk_register', sa.JSON(), nullable=False),
    sa.Column('roadmap', sa.JSON(), nullable=False),
    sa.Column('framework_gaps', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('generation_tokens_input', sa.Integer(), nullable=True),
    sa.Column('generation_tokens_output', sa.Integer(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_assessment_id'), 'reports', ['assessment_id'], unique=False)
    op.create_table('roadmap_items',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('source_task_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('effort', sa.String(length=20), nullable=False),
    sa.Column('week_target', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED', name='roadmapstatus'), nullable=False),
    sa.Column('assignee_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('framework_citations', sa.JSON(), nullable=False),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('addresses_risk_ids', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'source_task_id', name='uq_roadmap_report_source_task')
    )
    op.create_index(op.f('ix_roadmap_items_company_id'), 'roadmap_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_roadmap_items_report_id'), 'roadmap_items', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_items_report_id'), table_name='roadmap_items')
    op.drop_index(op.f('ix_roadmap_items_company_id'), table_name='roadmap_items')
    op.drop_table('roadmap_items')
    op.drop_index(op.f('ix_reports_assessment_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_policy_acknowledgments_user_id'), table_name='policy_acknowledgments')
    op.drop_index(op.f('ix_policy_acknowledgments_policy_id'), table_name='policy_acknowledgments')
    op.drop_table('policy_acknowledgments')
    op.drop_index(op.f('ix_evidence_framework_code'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_control_code'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_company_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_control_mappings_target_control_id'), table_name='control_mappings')
    op.drop_index(op.f('ix_control_mappings_source_control_id'), table_name='control_mappings')
    op.drop_table('control_mappings')
    op.drop_index(op.f('ix_billing_events_subscription_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_paystack_event_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_type'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_company_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index(op.f('ix_assessments_company_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_paystack_subscription_code'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_company_status', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_company_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_policies_template_code'), table_name='policies')
    op.drop_index(op.f('ix_policies_company_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_controls_framework_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_frameworks_code'), table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
